# Change these first
owner: hmu332233 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: blog
    url: https://blog-new.minung.dev
  - name: gatsby-starter
    url: https://gatsby-starter-minung.vercel.app
  - name: help-jbnu--page
    url: https://help-jbnu--page.minung.dev
  - name: q-link
    url: https://q-link.minung.dev
  - name: moon.svg
    url: https://moon-svg.minung.dev
  - name: dday.widget
    url: https://dday-widget.minung.dev
  - name: tip-tap
    url: https://tip-tap.minung.dev
  - name: celebration
    url: https://celebration.minung.dev
  - name: web-recorder
    url: https://web-recorder.minung.dev
  - name: peer-voice
    url: https://peer-voice.minung.dev
  - name: tips
    url: https://tips.minung.dev
  - name: lecture-ranking
    url: https://lecture-ranking.vercel.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.minung.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
